---
# This playbook deploys the whole application stack

- name: Apply common configuration to all raspberry pi nodes
  hosts: all
  remote_user: pi
  become: yes

  roles: 
    - pi

- name: Configure and deploy PiHole on raspberry pi nodes
  hosts: piholes
  remote_user: pi
  become: yes

  roles:
    - pihole

- name: Configure and DNSMasq and local network hostnames
  hosts: dnsservers
  remote_user: pi
  become: yes

  roles:
    - dns
