---

- name: "Create pihole Group"
  group:
    name: pihole
    state: present
  tags: pihole

- name: "Create pihole User"
  user:
    name: pihole
    group: pihole
    shell: /bin/bash
    state: present
  tags: pihole

- name: "Download Pi-Hole installer"
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740
  tags: pihole

- name: "Create PiHole config directory"
  become: True
  file:
    name="{{ fspath_pihole_config }}"
    state=directory
    owner="{{ user_pihole }}"
    group="{{ group_pihole }}"
    mode=0755
  tags: pihole

- name: "Configure Pi-Hole"
  become: True
  template:
    src="setupVars.conf.j2"
    dest="{{ fspath_pihole_config }}/setupVars.conf"
    owner=root
    group=root
    mode=0644
  tags: pihole

- name: "Set static IP config"
  become: True
  template:
    src="setupVars.conf.j2"
    dest="{{ fspath_pihole_config }}/setupVars.conf"
    owner=root
    group=root
    mode=0644
  tags: admin

- name: "Install Pi-Hole"
  shell: "~/install-pihole.sh --unattended"
  register: dbg_install_pihole
  tags: pihole

- name: "Configure Pi-Hole to auto-update weekly"
  become: True
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*$'
    replace: '\1'
    backup: yes
  tags: pihole
